import React, { createContext, useContext, useCallback, useMemo, useState, useEffect } from "react";
import { doc, setDoc, collection, query, where, getDocs, updateDoc, deleteDoc, orderBy, Timestamp, onSnapshot, getDoc, arrayUnion } from "../services/postgresFirestoreCompat";
import { db } from "../services/firebase";
import { useAuth, Profile, Class, PaymentNotification } from "./AuthContext";

// Função segura para formatar data no formato DD/MM/YYYY
const formatDateSafe = (dateStr: any): string => {
  if (!dateStr || typeof dateStr !== 'string') return '--/--/----';
  try {
    return dateStr.split("-").reverse().join("/");
  } catch {
    return '--/--/----';
  }
};

// ==================== TIPOS ====================

export type PaymentStatus = "pending" | "paid" | "overdue" | "cancelled";

export type PaymentMethod = "pix" | "pix_mercadopago" | "cash" | "card" | "transfer";

export type InvoiceType = "mensalidade" | "baile" | "workshop" | "outro";

// Voucher para bailes
export type BaileVoucher = {
  id: string;
  invoiceId: string;
  studentId: string;
  studentName: string;
  studentEmail: string;
  eventName: string;
  eventDate?: string;
  voucherCode: string; // Código único do voucher
  status: "valid" | "used" | "cancelled";
  createdAt: number;
  usedAt?: number;
  usedBy?: string; // Quem validou o voucher
  // Campos para voucher de acompanhante
  isGuest?: boolean; // true se for voucher de acompanhante
  guestName?: string; // Nome do acompanhante
  parentVoucherId?: string; // ID do voucher principal (do aluno)
  guestPrice?: number; // Preço pago pelo voucher de acompanhante (em centavos)
};

// Cobrança/Fatura
export type Invoice = {
  id: string;
  studentId: string;
  studentName: string;
  studentEmail: string;
  amount: number; // em centavos - valor atual a pagar
  originalAmount: number; // valor sem desconto (em centavos)
  discountAmount: number; // valor do desconto (em centavos)
  description: string;
  dueDate: string; // "YYYY-MM-DD" - data limite para desconto
  lateDueDate: string; // "YYYY-MM-DD" - data limite final
  status: PaymentStatus;
  referenceMonth: string; // "2025-01" (para mensalidades)
  classIds?: string[]; // turmas relacionadas
  classCount: number; // número de turmas
  createdAt: number;
  createdBy: string;
  updatedAt?: number;
  paidAt?: number;
  paidMethod?: PaymentMethod;
  pixCode?: string; // Código PIX gerado
  pixExpiration?: number; // Timestamp de expiração do PIX
  notes?: string;
  // Tipo de cobrança
  type?: InvoiceType; // mensalidade, baile, workshop, outro
  // Voucher gerado (para bailes)
  voucherId?: string;
  // Flags de controle
  isAutoGenerated?: boolean; // gerada automaticamente
  // Mercado Pago específico
  mpPaymentId?: number; // ID do pagamento no Mercado Pago
  mpStatus?: string; // Status no Mercado Pago (pending, approved, etc)
  pixQrCodeBase64?: string; // QR Code em base64 do MP
  pixTicketUrl?: string; // URL do ticket de pagamento
  pixExpiresAt?: number; // Timestamp de expiração do PIX MP
  // Campos para ingresso de acompanhante
  isGuestTicket?: boolean; // true se for ingresso de acompanhante
  guestName?: string; // Nome do acompanhante
  parentVoucherId?: string; // ID do voucher principal (do aluno)
};

// Transação (entrada ou saída)
export type Transaction = {
  id: string;
  type: "income" | "expense";
  category: string; // "mensalidade", "material", "salario", "aluguel", etc.
  description: string;
  amount: number; // em centavos - valor bruto recebido
  amountNet?: number; // em centavos - valor líquido após dedução de taxas (valor que está na conta do banco)
  fee?: number; // em centavos - taxa deduzida pelo Mercado Pago
  feePercentage?: number; // porcentagem da taxa aplicada
  date: string; // "YYYY-MM-DD"
  invoiceId?: string; // referência à fatura (se for pagamento)
  studentId?: string;
  studentName?: string;
  teacherId?: string;
  teacherName?: string;
  paymentMethod?: PaymentMethod;
  createdAt: number;
  createdBy: string;
  notes?: string;
};

// Preço por número de turmas
export type TierPricing = {
  classes: number; // número de turmas
  earlyPrice: number; // preço com desconto (em centavos)
  regularPrice: number; // preço normal (em centavos)
};

// Configurações de pagamento
export type PaymentSettings = {
  monthlyFee: number; // valor padrão da mensalidade em centavos (1 turma, sem desconto)
  pixKey: string; // chave PIX do estabelecimento
  pixKeyType: "cpf" | "cnpj" | "email" | "phone" | "random";
  pixReceiverName: string; // nome do recebedor
  pixCity: string; // cidade do recebedor
  dueDayOfMonth: number; // dia do vencimento com desconto (ex: dia 1)
  gracePeriodDays: number; // dias de tolerância antes de marcar como atrasado
  latePaymentDeadline: number; // último dia para pagamento (ex: dia 8)
  // Tabela de preços por turmas
  tierPricing: TierPricing[];
  // Taxas do Mercado Pago (em porcentagem, ex: 1.0 = 1%)
  mercadoPagoTaxPix: number; // taxa do PIX via Mercado Pago (padrão: 1.0%)
  mercadoPagoTaxCard: number; // taxa do cartão via Mercado Pago (padrão: 4.99%)
  mercadoPagoTaxOther: number; // taxa de outros métodos via Mercado Pago (padrão: 1.0%)
  // Controle de atualização
  updatedAt?: number;
};

// Resumo financeiro
export type FinancialSummary = {
  totalReceived: number; // valor bruto recebido (antes das taxas)
  totalFees: number; // total de taxas deduzidas
  totalReceivedNet: number; // valor líquido recebido (após taxas) - valor que está na conta
  totalPending: number;
  totalOverdue: number;
  totalExpenses: number;
  balance: number; // saldo líquido (totalReceivedNet - totalExpenses)
  invoicesCount: {
    paid: number;
    pending: number;
    overdue: number;
  };
};

// ==================== CONTEXTO ====================

type PaymentContextType = {
  // Faturas
  createInvoice: (data: Omit<Invoice, "id" | "createdAt" | "createdBy" | "status">) => Promise<string>;
  fetchInvoices: (filters?: { studentId?: string; status?: PaymentStatus; month?: string }) => Promise<Invoice[]>;
  updateInvoice: (id: string, data: Partial<Invoice>) => Promise<void>;
  deleteInvoice: (id: string) => Promise<void>;
  markAsPaid: (invoiceId: string, method: PaymentMethod, notes?: string) => Promise<void>;
  markAsOverdue: (invoiceId: string) => Promise<void>;
  
  // Transações
  createTransaction: (data: Omit<Transaction, "id" | "createdAt" | "createdBy">) => Promise<string>;
  fetchTransactions: (filters?: { type?: "income" | "expense"; month?: string }) => Promise<Transaction[]>;
  deleteTransaction: (id: string) => Promise<void>;
  
  // PIX
  generatePixCode: (invoice: Invoice) => Promise<string>;
  
  // Relatórios
  getFinancialSummary: (month?: string) => Promise<FinancialSummary>;
  
  // Cobranças em lote
  generateMonthlyInvoices: (students: Profile[], month: string) => Promise<number>;
  
  // Atualização automática de status
  updateOverdueInvoices: () => Promise<number>;
  
  // Configurações
  getPaymentSettings: () => Promise<PaymentSettings | null>;
  updatePaymentSettings: (settings: Partial<PaymentSettings>) => Promise<void>;
  
  // Cálculo de preços
  calculatePriceForStudent: (classCount: number, settings: PaymentSettings) => { earlyPrice: number; regularPrice: number; discount: number };
  
  // Geração automática de fatura para aluno
  generateInvoiceForStudent: (student: Profile, month: string) => Promise<Invoice | null>;
  
  // Listeners em tempo real
  subscribeToInvoices: (studentId: string, callback: (invoices: Invoice[]) => void) => () => void;
  subscribeToAllInvoices: (callback: (invoices: Invoice[]) => void, filters?: { status?: PaymentStatus | PaymentStatus[]; month?: string }) => () => void;
  subscribeToSettings: (callback: (settings: PaymentSettings | null) => void) => () => void;
  
  // Administração
  clearAllFinancialData: () => Promise<{ invoices: number; transactions: number; studentsUpdated: number }>;
  migrateTransactionsAmountNet: () => Promise<{ updated: number; skipped: number }>;

  // Vouchers
  createBaileVoucher: (invoice: Invoice) => Promise<BaileVoucher>;
  fetchVoucherByEventId: (eventId: string, studentId: string) => Promise<BaileVoucher | null>;
  cancelVoucher: (voucherId: string) => Promise<void>;
  deleteVoucher: (voucherId: string) => Promise<void>;

  // Vouchers de acompanhante
  createGuestInvoice: (parentVoucher: BaileVoucher, guestName: string, guestPrice: number) => Promise<Invoice>;
  createGuestVoucher: (invoice: Invoice, parentVoucher: BaileVoucher, guestName: string) => Promise<BaileVoucher>;
  fetchGuestVouchers: (parentVoucherId: string) => Promise<BaileVoucher[]>;
};

const PaymentContext = createContext<PaymentContextType>({} as PaymentContextType);

// ==================== FUNÇÕES AUXILIARES ====================

// Formata valor de centavos para BRL
export function formatCurrency(cents: number | undefined | null): string {
  if (cents === undefined || cents === null || isNaN(cents)) {
    return "R$ 0,00";
  }
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
  }).format(cents / 100);
}

// Converte reais para centavos
export function toCents(value: number): number {
  return Math.round(value * 100);
}

// Converte centavos para reais
export function toReais(cents: number): number {
  return cents / 100;
}

// Gera ID único
function generateId(prefix: string): string {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}

// Verifica se uma data está vencida
function isOverdue(dueDate: string): boolean {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const due = new Date(dueDate + "T00:00:00");
  return due < today;
}

// Nome do mês em português
function getMonthName(month: number): string {
  const months = [
    "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
    "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"
  ];
  return months[month - 1] || "";
}

// Gera payload PIX (EMV QR Code estático simplificado)
function generatePixPayload(
  pixKey: string,
  pixKeyType: string,
  receiverName: string,
  city: string,
  amount: number,
  txId: string,
  description: string
): string {
  // Implementação simplificada do payload PIX
  // Em produção, usar biblioteca específica como 'pix-payload' ou API do banco
  
  const amountStr = (amount / 100).toFixed(2);
  
  // Monta payload EMV
  const payload = [
    "00020126", // Payload Format Indicator
    formatEMVField("26", [
      "0014BR.GOV.BCB.PIX",
      formatEMVField("01", pixKey),
    ].join("")),
    "52040000", // Merchant Category Code
    "5303986", // Transaction Currency (986 = BRL)
    formatEMVField("54", amountStr),
    "5802BR", // Country Code
    formatEMVField("59", receiverName.substring(0, 25)),
    formatEMVField("60", city.substring(0, 15)),
    formatEMVField("62", formatEMVField("05", txId.substring(0, 25))),
  ].join("");
  
  // Adiciona CRC16
  const crc = calculateCRC16(payload + "6304");
  return payload + "6304" + crc;
}

function formatEMVField(id: string, value: string): string {
  const len = value.length.toString().padStart(2, "0");
  return id + len + value;
}

function calculateCRC16(str: string): string {
  // CRC16-CCITT-FALSE
  let crc = 0xFFFF;
  for (let i = 0; i < str.length; i++) {
    crc ^= str.charCodeAt(i) << 8;
    for (let j = 0; j < 8; j++) {
      if (crc & 0x8000) {
        crc = (crc << 1) ^ 0x1021;
      } else {
        crc <<= 1;
      }
    }
  }
  return (crc & 0xFFFF).toString(16).toUpperCase().padStart(4, "0");
}

// ==================== PROVIDER ====================

export function PaymentProvider({ children }: { children: React.ReactNode }) {
  const { profile, confirmEventAttendanceAfterPayment } = useAuth();

  // Extract primitive values to use as stable dependencies
  const profileUid = profile?.uid;
  const profileRole = profile?.role;

  // Função auxiliar para criar atividades diretamente (evita dependência circular com ActivityContext)
  const createActivity = useCallback(async (activityData: {
    type: string;
    title: string;
    description: string;
    metadata?: any;
  }): Promise<void> => {
    if (!profileUid) return;

    try {
      const activityId = `ACT_${Date.now()}_${Math.random().toString(36).substr(2, 6)}`;
      await setDoc(doc(db, "activities", activityId), {
        id: activityId,
        ...activityData,
        timestamp: Date.now(),
        read: false,
        createdBy: profileUid,
      });
    } catch (e) {
      console.warn("Erro ao criar atividade:", e);
    }
  }, [profileUid]);
  
  // Função auxiliar para calcular taxa do Mercado Pago baseado no método de pagamento
  const calculateMercadoPagoFee = useCallback((
    amount: number,
    paymentMethod: PaymentMethod,
    settings?: PaymentSettings | null
  ): { fee: number; feePercentage: number; amountNet: number } => {
    // Valores padrão de taxa (em porcentagem)
    const defaultPixFee = 1.0; // 1% para PIX via Mercado Pago
    const defaultCardFee = 4.99; // 4.99% para cartão via Mercado Pago
    const defaultOtherFee = 1.0; // 1% para outros métodos via Mercado Pago

    // Se o pagamento não for via Mercado Pago, não há taxa
    if (paymentMethod !== "pix_mercadopago" && paymentMethod !== "card") {
      return { fee: 0, feePercentage: 0, amountNet: amount };
    }

    // Obtém taxa das configurações ou usa padrão
    let feePercentage = 0;
    if (paymentMethod === "pix_mercadopago") {
      feePercentage = settings?.mercadoPagoTaxPix ?? defaultPixFee;
    } else if (paymentMethod === "card") {
      feePercentage = settings?.mercadoPagoTaxCard ?? defaultCardFee;
    } else {
      feePercentage = settings?.mercadoPagoTaxOther ?? defaultOtherFee;
    }

    // Calcula a taxa em centavos
    const fee = Math.round(amount * (feePercentage / 100));
    const amountNet = amount - fee;

    return { fee, feePercentage, amountNet };
  }, [profileRole, profileUid]);

  // ========== FATURAS ==========

  // Tipos de notificação relacionados a cobrança (devem ser únicos por fatura)
  const BILLING_NOTIFICATION_TYPES = ["billing", "pending_invoice", "reminder", "overdue"];
  
  // Envia notificação para o perfil do aluno
  // Se já existir uma notificação de cobrança para a mesma fatura, substitui pelo novo status
  const sendNotificationToStudent = useCallback(async (
    studentId: string,
    notification: Omit<PaymentNotification, "id" | "createdAt" | "createdBy">
  ): Promise<void> => {
    if (!profileUid) return;
    
    try {
      const studentRef = doc(db, "profiles", studentId);
      const studentSnap = await getDoc(studentRef);
      
      if (!studentSnap.exists()) {
        console.warn(`Perfil do aluno ${studentId} não encontrado para enviar notificação`);
        return;
      }
      
      const studentData = studentSnap.data() as Profile;
      
      // Não envia notificação para alunos offline (não têm acesso ao app)
      if (studentData.isOffline) {
        return;
      }
      
      const existingNotifications: PaymentNotification[] = studentData.pendingNotifications || [];
      const isBillingNotification = BILLING_NOTIFICATION_TYPES.includes(notification.type);
      
      // Se for notificação de cobrança e tem invoiceId, verifica duplicatas
      if (isBillingNotification && notification.invoiceId) {
        // Verifica se já existe uma notificação de cobrança para esta fatura
        const existingIndex = existingNotifications.findIndex(
          n => n.invoiceId === notification.invoiceId && BILLING_NOTIFICATION_TYPES.includes(n.type)
        );
        
        if (existingIndex !== -1) {
          const existingNotif = existingNotifications[existingIndex];
          
          // Se o tipo é o mesmo, não faz nada (evita duplicata exata)
          if (existingNotif.type === notification.type) {
            console.log(`Notificação ${notification.type} já existe para fatura ${notification.invoiceId}`);
            return;
          }
          
          // Substitui a notificação existente pelo novo status
          const updatedNotifications = [...existingNotifications];
          updatedNotifications[existingIndex] = {
            ...notification,
            id: existingNotif.id, // Mantém o mesmo ID
            createdAt: Date.now(), // Atualiza timestamp
            createdBy: profileUid,
          };
          
          await updateDoc(studentRef, {
            pendingNotifications: updatedNotifications,
          });
          
          console.log(`Notificação atualizada de ${existingNotif.type} para ${notification.type} - ${studentData.name}`);
          return;
        }
      }
      
      // Se for notificação de pagamento confirmado, remove notificações de cobrança da mesma fatura
      if (notification.type === "payment_confirmed" && notification.invoiceId) {
        const filteredNotifications = existingNotifications.filter(
          n => !(n.invoiceId === notification.invoiceId && BILLING_NOTIFICATION_TYPES.includes(n.type))
        );
        
        const fullNotification: PaymentNotification = {
          ...notification,
          id: generateId("NOTIF"),
          createdAt: Date.now(),
          createdBy: profileUid,
        };

        await updateDoc(studentRef, {
          pendingNotifications: [...filteredNotifications, fullNotification],
        });

        console.log(`Notificação de pagamento confirmado enviada para ${studentData.name}`);
        return;
      }

      // Caso padrão: adiciona nova notificação
      const fullNotification: PaymentNotification = {
        ...notification,
        id: generateId("NOTIF"),
        createdAt: Date.now(),
        createdBy: profileUid,
      };
      
      await updateDoc(studentRef, {
        pendingNotifications: [...existingNotifications, fullNotification],
      });
      
      console.log(`Notificação enviada para ${studentData.name}`);
    } catch (error) {
      console.error("Erro ao enviar notificação para aluno:", error);
    }
  }, [profileUid]);

  const createInvoice = useCallback(async (
    data: Omit<Invoice, "id" | "createdAt" | "createdBy" | "status">
  ): Promise<string> => {
    if (!profileUid) throw new Error("Usuário não autenticado");

    const id = generateId("INV");
    const invoice: Invoice = {
      ...data,
      id,
      status: "pending",
      createdAt: Date.now(),
      createdBy: profileUid,
    };

    await setDoc(doc(db, "invoices", id), invoice);
    
    // Envia notificação para o aluno
    await sendNotificationToStudent(data.studentId, {
      type: "billing",
      title: "Nova cobrança gerada",
      message: `Uma cobrança de ${formatCurrency(data.amount)} foi gerada para você.`,
      invoiceId: id,
      amount: data.amount,
      dueDate: data.dueDate,
    });
    
    // Cria atividade para o log de atividades recentes
    try {
      const activityId = generateId("ACT");
      const activitiesRef = collection(db, "activities");
      await setDoc(doc(activitiesRef, activityId), {
        id: activityId,
        type: "invoice_generated",
        title: "Cobrança personalizada gerada",
        description: `Cobrança de ${formatCurrency(data.amount)} gerada para ${data.studentName}`,
        timestamp: Date.now(),
        metadata: {
          studentId: data.studentId,
          studentName: data.studentName,
          invoiceId: id,
          amount: data.amount,
        },
        read: false,
        createdBy: profileUid,
      });
    } catch (e) {
      console.warn("Erro ao criar atividade:", e);
    }

    return id;
  }, [profileUid, sendNotificationToStudent]);

  const fetchInvoices = useCallback(async (
    filters?: { studentId?: string; status?: PaymentStatus; month?: string }
  ): Promise<Invoice[]> => {
    try {
      const invoicesRef = collection(db, "invoices");
      let constraints: any[] = [];

      // IMPORTANTE: Para students, SEMPRE filtrar por seu próprio studentId
      // Isso é necessário para satisfazer as regras de segurança do Firestore
      if (profile?.role === "student") {
        // Student só pode ver suas próprias faturas
        constraints.push(where("studentId", "==", profile.uid));
      } else if (filters?.studentId) {
        // Para master/teacher, usa o filtro fornecido se houver
        constraints.push(where("studentId", "==", filters.studentId));
      }
      
      if (filters?.status) {
        constraints.push(where("status", "==", filters.status));
      }
      if (filters?.month) {
        constraints.push(where("referenceMonth", "==", filters.month));
      }

      const q = constraints.length > 0 
        ? query(invoicesRef, ...constraints)
        : query(invoicesRef);
      
      const snap = await getDocs(q);
      const invoices = snap.docs.map(d => d.data() as Invoice);
      
      // Ordena por data de vencimento
      return invoices.sort((a, b) => 
        new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime()
      );
    } catch (e) {
      console.error("Erro ao buscar faturas:", e);
      return [];
    }
  }, [profile?.role, profile?.uid]);

  const updateInvoice = useCallback(async (id: string, data: Partial<Invoice>): Promise<void> => {
    const ref = doc(db, "invoices", id);
    await updateDoc(ref, { ...data, updatedAt: Date.now() });
  }, [profileRole, profileUid]);

  const deleteInvoice = useCallback(async (id: string): Promise<void> => {
    if (!profileUid) throw new Error("Usuário não autenticado");

    // Busca os dados da fatura antes de deletar
    const invoiceRef = doc(db, "invoices", id);
    const invoiceSnap = await getDoc(invoiceRef);
    
    if (!invoiceSnap.exists()) {
      throw new Error("Fatura não encontrada");
    }

    const invoice = invoiceSnap.data() as Invoice;

    // Remove notificações de cobrança relacionadas à fatura do perfil do aluno
    if (invoice.studentId) {
      try {
        const studentRef = doc(db, "profiles", invoice.studentId);
        const studentSnap = await getDoc(studentRef);
        
        if (studentSnap.exists()) {
          const studentData = studentSnap.data() as Profile;
          const existingNotifications: PaymentNotification[] = studentData.pendingNotifications || [];
          
          // Remove notificações de cobrança relacionadas a esta fatura
          const filteredNotifications = existingNotifications.filter(
            n => !(n.invoiceId === id && BILLING_NOTIFICATION_TYPES.includes(n.type))
          );
          
          // Adiciona notificação de cobrança removida
          const deletedNotification: PaymentNotification = {
            id: generateId("NOTIF"),
            type: "invoice_deleted",
            title: "Cobrança removida",
            message: `A cobrança de ${formatCurrency(invoice.amount)} (${invoice.description || "sem descrição"}) foi removida.`,
            invoiceId: id,
            amount: invoice.amount,
            createdAt: Date.now(),
            createdBy: profileUid,
          };
          
          await updateDoc(studentRef, {
            pendingNotifications: [...filteredNotifications, deletedNotification],
          });
        }
      } catch (e) {
        console.warn("Erro ao enviar notificação para o aluno:", e);
      }
    }

    // Cria atividade para o log de atividades recentes (para administrador)
    try {
      const activityId = generateId("ACT");
      const activitiesRef = collection(db, "activities");
      await setDoc(doc(activitiesRef, activityId), {
        id: activityId,
        type: "invoice_deleted",
        title: "Cobrança removida",
        description: `Cobrança de ${formatCurrency(invoice.amount)} removida para ${invoice.studentName}`,
        timestamp: Date.now(),
        metadata: {
          studentId: invoice.studentId,
          studentName: invoice.studentName,
          invoiceId: id,
          amount: invoice.amount,
        },
        read: false,
        createdBy: profileUid,
      });
    } catch (e) {
      console.warn("Erro ao criar atividade:", e);
    }

    // Deleta a fatura
    await deleteDoc(invoiceRef);
  }, [profileUid]);

  // ========== VOUCHERS DE BAILE ==========

  // Gera código único de voucher
  const generateVoucherCode = (): string => {
    const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
    let code = "BAILE-";
    for (let i = 0; i < 8; i++) {
      code += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return code;
  };

  // Cria voucher para baile
  const createBaileVoucher = useCallback(async (invoice: Invoice): Promise<BaileVoucher> => {
    if (!profileUid) {
      console.error("[createBaileVoucher] Usuário não autenticado");
      throw new Error("Usuário não autenticado");
    }

    const id = generateId("VCH");
    const voucherCode = generateVoucherCode();

    const voucher: BaileVoucher = {
      id,
      invoiceId: invoice.id,
      studentId: invoice.studentId,
      studentName: invoice.studentName,
      studentEmail: invoice.studentEmail,
      eventName: invoice.description || "Baile CDMF",
      eventDate: invoice.dueDate, // Data do evento (para verificação de expiração)
      voucherCode,
      status: "valid",
      createdAt: Date.now(),
    };

    try {
      await setDoc(doc(db, "vouchers", id), voucher);
    } catch (voucherError: any) {
      console.error("[createBaileVoucher] ❌ ERRO ao criar voucher:", voucherError);
      throw new Error(`Erro ao criar voucher: ${voucherError.message}`);
    }

    try {
      await updateDoc(doc(db, "invoices", invoice.id), {
        voucherId: id,
      });
    } catch (updateError: any) {
      console.error("[createBaileVoucher] ❌ ERRO ao atualizar invoice:", updateError);
      console.error("[createBaileVoucher] Código do erro:", updateError.code);
      console.error("[createBaileVoucher] Mensagem do erro:", updateError.message);
      throw new Error(`Erro ao atualizar invoice: ${updateError.message}`);
    }

    return voucher;
  }, [profileUid]);

  // Busca vouchers do aluno (filtra vouchers expirados há mais de 30 dias)
  const fetchStudentVouchers = useCallback(async (studentId: string): Promise<BaileVoucher[]> => {
    const vouchersRef = collection(db, "vouchers");
    const q = query(vouchersRef, where("studentId", "==", studentId), orderBy("createdAt", "desc"));
    const snap = await getDocs(q);
    const vouchers = snap.docs.map(d => d.data() as BaileVoucher);

    const now = new Date();
    const threeDaysMs = 3 * 24 * 60 * 60 * 1000;

    // Filtra e apaga vouchers expirados há mais de 3 dias após o evento
    const vouchersToKeep: BaileVoucher[] = [];

    for (const voucher of vouchers) {
      let eventEndDate: Date | null = null;

      // Determina a data do evento
      if (voucher.eventDate) {
        try {
          const dateOnly = voucher.eventDate.split('T')[0];
          const [year, month, day] = dateOnly.split('-').map(Number);
          eventEndDate = new Date(Date.UTC(year, month - 1, day, 23, 59, 59));
        } catch (e) {
          // Se falhar, mantém o voucher
        }
      }

      // Apaga vouchers de eventos realizados há mais de 3 dias
      if (eventEndDate) {
        const timeSinceEvent = now.getTime() - eventEndDate.getTime();

        if (timeSinceEvent > threeDaysMs) {
          try {
            await deleteDoc(doc(db, "vouchers", voucher.id));
            console.log(`[Voucher] Voucher ${voucher.id} apagado (evento realizado há mais de 3 dias)`);
          } catch (e) {
            console.warn(`Erro ao apagar voucher ${voucher.id}:`, e);
          }
          continue;
        }
      }

      vouchersToKeep.push(voucher);
    }

    return vouchersToKeep;
  }, []);

  // Busca voucher por invoiceId
  const fetchVoucherByInvoiceId = useCallback(async (invoiceId: string): Promise<BaileVoucher | null> => {
    const vouchersRef = collection(db, "vouchers");
    // Se o usuário for aluno, adiciona filtro por studentId para satisfazer as regras de segurança
    const q = profileUid && profile?.role === 'student'
      ? query(vouchersRef, where("invoiceId", "==", invoiceId), where("studentId", "==", profileUid))
      : query(vouchersRef, where("invoiceId", "==", invoiceId));
    const snap = await getDocs(q);
    if (snap.empty) return null;
    return snap.docs[0].data() as BaileVoucher;
  }, [profileUid, profile?.role]);

  // Busca voucher por eventId e studentId (para vouchers criados manualmente sem invoice)
  const fetchVoucherByEventId = useCallback(async (eventId: string, studentId: string): Promise<BaileVoucher | null> => {
    const vouchersRef = collection(db, "vouchers");
    
    // Primeiro tenta buscar por eventId se o campo existir
    try {
      const qWithEventId = query(
        vouchersRef,
        where("studentId", "==", studentId),
        where("eventId", "==", eventId),
        where("status", "==", "valid")
      );
      const snapWithEventId = await getDocs(qWithEventId);
      if (!snapWithEventId.empty) {
        return snapWithEventId.docs[0].data() as BaileVoucher & { eventId?: string };
      }
    } catch (e) {
      // Se o campo eventId não existir em alguns vouchers antigos, continua
    }
    
    return null;
  }, []);

  // Valida/usa voucher (para entrada no baile)
  const useVoucher = useCallback(async (voucherCode: string): Promise<BaileVoucher | null> => {
    if (!profileUid) throw new Error("Usuário não autenticado");

    const vouchersRef = collection(db, "vouchers");
    const q = query(vouchersRef, where("voucherCode", "==", voucherCode));
    const snap = await getDocs(q);

    if (snap.empty) {
      return null;
    }

    const voucherDoc = snap.docs[0];
    const voucher = voucherDoc.data() as BaileVoucher;

    if (voucher.status === "used") {
      throw new Error("Este voucher já foi utilizado!");
    }

    if (voucher.status === "cancelled") {
      throw new Error("Este voucher foi cancelado.");
    }

    // Marca como usado
    await updateDoc(doc(db, "vouchers", voucher.id), {
      status: "used",
      usedAt: Date.now(),
      usedBy: profileUid,
    });

    return { ...voucher, status: "used", usedAt: Date.now(), usedBy: profileUid };
  }, [profileUid]);

  // Cancela voucher (marca como cancelado)
  const cancelVoucher = useCallback(async (voucherId: string): Promise<void> => {
    await updateDoc(doc(db, "vouchers", voucherId), {
      status: "cancelled",
    });
  }, []);

  // Deleta voucher completamente
  const deleteVoucher = useCallback(async (voucherId: string): Promise<void> => {
    await deleteDoc(doc(db, "vouchers", voucherId));
  }, []);

  // Busca todos os vouchers (para admin)
  const fetchAllVouchers = useCallback(async (): Promise<BaileVoucher[]> => {
    const vouchersRef = collection(db, "vouchers");
    const q = query(vouchersRef, orderBy("createdAt", "desc"));
    const snap = await getDocs(q);
    return snap.docs.map(d => d.data() as BaileVoucher);
  }, []);

  // ========== VOUCHERS DE ACOMPANHANTE ==========

  // Cria invoice para voucher de acompanhante
  const createGuestInvoice = useCallback(async (
    parentVoucher: BaileVoucher,
    guestName: string,
    guestPrice: number
  ): Promise<Invoice> => {
    if (!profileUid) throw new Error("Usuário não autenticado");

    const id = generateId("INV");
    const invoice: Invoice = {
      id,
      studentId: parentVoucher.studentId,
      studentName: parentVoucher.studentName,
      studentEmail: parentVoucher.studentEmail,
      amount: guestPrice,
      originalAmount: guestPrice,
      discountAmount: 0,
      description: `Ingresso Acompanhante: ${guestName} - ${parentVoucher.eventName}`,
      dueDate: parentVoucher.eventDate || new Date().toISOString().split("T")[0],
      lateDueDate: parentVoucher.eventDate || new Date().toISOString().split("T")[0],
      status: "pending",
      referenceMonth: new Date().toISOString().slice(0, 7),
      classCount: 0,
      createdAt: Date.now(),
      createdBy: profileUid,
      type: "baile",
      // Campos para identificar como ingresso de acompanhante
      isGuestTicket: true,
      guestName: guestName,
      parentVoucherId: parentVoucher.id,
    };

    await setDoc(doc(db, "invoices", id), invoice);

    // Envia notificação para o aluno
    await sendNotificationToStudent(parentVoucher.studentId, {
      type: "billing",
      title: "Ingresso de Acompanhante",
      message: `Cobrança de ${formatCurrency(guestPrice)} gerada para o acompanhante ${guestName}.`,
      invoiceId: id,
      amount: guestPrice,
      dueDate: invoice.dueDate,
    });

    return invoice;
  }, [profileUid, sendNotificationToStudent]);

  // Cria voucher de acompanhante (após pagamento)
  const createGuestVoucher = useCallback(async (
    invoice: Invoice,
    parentVoucher: BaileVoucher,
    guestName: string
  ): Promise<BaileVoucher> => {
    if (!profileUid) throw new Error("Usuário não autenticado");

    const id = generateId("VCH");
    const voucherCode = generateVoucherCode();

    const voucher: BaileVoucher = {
      id,
      invoiceId: invoice.id,
      studentId: parentVoucher.studentId,
      studentName: guestName,
      studentEmail: parentVoucher.studentEmail,
      eventName: parentVoucher.eventName,
      eventDate: parentVoucher.eventDate,
      voucherCode,
      status: "valid",
      createdAt: Date.now(),
      isGuest: true,
      guestName: guestName,
      parentVoucherId: parentVoucher.id,
      guestPrice: invoice.amount,
    };

    await setDoc(doc(db, "vouchers", id), voucher);

    // Atualiza a invoice com o voucherId
    await updateDoc(doc(db, "invoices", invoice.id), {
      voucherId: id,
    });

    return voucher;
  }, [profileUid]);

  // Busca vouchers de acompanhantes vinculados a um voucher principal
  const fetchGuestVouchers = useCallback(async (parentVoucherId: string): Promise<BaileVoucher[]> => {
    const vouchersRef = collection(db, "vouchers");
    const q = query(
      vouchersRef,
      where("parentVoucherId", "==", parentVoucherId),
      where("isGuest", "==", true)
    );
    const snap = await getDocs(q);
    return snap.docs.map(d => d.data() as BaileVoucher);
  }, []);

  // ========== CONFIGURAÇÕES ==========
  
  // Valores padrão para teste (abaixo de R$ 10)
  const DEFAULT_TIER_PRICING: TierPricing[] = [
    { classes: 1, earlyPrice: 990, regularPrice: 1090 },   // R$ 9,90 | R$ 10,90
    { classes: 2, earlyPrice: 1780, regularPrice: 1980 },  // R$ 17,80 | R$ 19,80
    { classes: 3, earlyPrice: 2520, regularPrice: 2820 },  // R$ 25,20 | R$ 28,20
    { classes: 4, earlyPrice: 3160, regularPrice: 3560 },  // R$ 31,60 | R$ 35,60
  ];

  const getPaymentSettings = useCallback(async (): Promise<PaymentSettings | null> => {
    try {
      const settingsRef = collection(db, "settings");
      const q = query(settingsRef, where("type", "==", "payment"));
      const snap = await getDocs(q);
      
      if (snap.empty) {
        // Retorna configurações padrão para teste
        return {
          monthlyFee: 1090, // R$ 10,90 (1 turma, preço normal)
          pixKey: "",
          pixKeyType: "cpf",
          pixReceiverName: "CDMF",
          pixCity: "SAO PAULO",
          dueDayOfMonth: 1, // dia 1 para desconto
          gracePeriodDays: 7, // até dia 8
          latePaymentDeadline: 8, // último dia
          tierPricing: DEFAULT_TIER_PRICING,
          // Taxas padrão do Mercado Pago (em porcentagem)
          mercadoPagoTaxPix: 1.0, // 1% para PIX via Mercado Pago
          mercadoPagoTaxCard: 4.99, // 4.99% para cartão via Mercado Pago
          mercadoPagoTaxOther: 1.0, // 1% para outros métodos via Mercado Pago
        };
      }
      
      const data = snap.docs[0].data() as PaymentSettings;
      // Garante que tierPricing existe
      if (!data.tierPricing || data.tierPricing.length === 0) {
        data.tierPricing = DEFAULT_TIER_PRICING;
      }
      // Garante que taxas existem (valores padrão se não configurados)
      if (data.mercadoPagoTaxPix === undefined) {
        data.mercadoPagoTaxPix = 1.0;
      }
      if (data.mercadoPagoTaxCard === undefined) {
        data.mercadoPagoTaxCard = 4.99;
      }
      if (data.mercadoPagoTaxOther === undefined) {
        data.mercadoPagoTaxOther = 1.0;
      }
      return data;
    } catch (e) {
      console.error("Erro ao buscar configurações:", e);
      return null;
    }
  }, []);

  const updatePaymentSettings = useCallback(async (settings: Partial<PaymentSettings>): Promise<void> => {
    const ref = doc(db, "settings", "payment");
    await setDoc(ref, { ...settings, type: "payment", updatedAt: Date.now() }, { merge: true });
  }, []);

  const markAsPaid = useCallback(async (
    invoiceId: string, 
    method: PaymentMethod, 
    notes?: string
  ): Promise<void> => {
    if (!profile) throw new Error("Usuário não autenticado");

    const ref = doc(db, "invoices", invoiceId);
    const now = Date.now();
    
    // Verifica se a fatura já foi paga (evita duplicidade)
    const invoiceSnap = await getDocs(query(collection(db, "invoices"), where("id", "==", invoiceId)));
    if (!invoiceSnap.empty) {
      const invoiceData = invoiceSnap.docs[0].data() as Invoice;
      if (invoiceData.status === "paid") {
        throw new Error("Esta fatura já foi paga!");
      }
      if (invoiceData.status === "cancelled") {
        throw new Error("Esta fatura foi cancelada e não pode ser paga.");
      }
    }
    
    // Busca configurações de pagamento para calcular taxas
    const settings = await getPaymentSettings();
    
    // Busca dados da fatura para calcular taxas
    const invoicesRef = collection(db, "invoices");
    const q = query(invoicesRef, where("id", "==", invoiceId));
    const snap = await getDocs(q);
    
    if (!snap.empty) {
      const invoice = snap.docs[0].data() as Invoice;
      
      // Calcula taxa do Mercado Pago se aplicável
      const { fee, feePercentage, amountNet } = calculateMercadoPagoFee(
        invoice.amount,
        method,
        settings
      );
      
      // Atualiza a fatura
      await updateDoc(ref, {
        status: "paid",
        paidAt: now,
        paidMethod: method,
        updatedAt: now,
        ...(notes ? { notes } : {}),
      });
      
      // Determina categoria baseado no tipo da invoice
      const category = invoice.type === "baile" || invoice.type === "outro" || 
                      invoice.type === "workshop" ||
                      invoice.description?.includes("Ingresso:") 
                        ? (invoice.type || "mensalidade") 
                        : "mensalidade";
      
      // Verifica se já existe transação para esta fatura (evita duplicação)
      const transactionsRef = collection(db, "transactions");
      const existingTransactionsQuery = query(
        transactionsRef,
        where("invoiceId", "==", invoiceId),
        where("type", "==", "income")
      );
      const existingTransactionsSnap = await getDocs(existingTransactionsQuery);
      
      if (existingTransactionsSnap.empty) {
        // Cria transação de entrada com valores brutos e líquidos
        const transactionId = generateId("TXN");
        const transaction: Transaction = {
          id: transactionId,
          type: "income",
          category: category,
          description: invoice.type === "baile" || invoice.type === "outro" || invoice.type === "workshop"
            ? `Pagamento - ${invoice.studentName} - ${invoice.description || category}`
            : `Pagamento - ${invoice.studentName} (${invoice.referenceMonth})`,
          amount: invoice.amount, // valor bruto cobrado
          amountNet: fee > 0 ? amountNet : invoice.amount, // valor líquido após taxa (se não houver taxa, é igual ao valor bruto)
          date: new Date().toISOString().split("T")[0],
          invoiceId,
          studentId: invoice.studentId,
          studentName: invoice.studentName,
          paymentMethod: method,
          createdAt: now,
          createdBy: profile.uid,
        };

        // Adiciona campos de taxa apenas se houver taxa (Firebase não aceita undefined)
        if (fee > 0) {
          transaction.fee = fee;
          transaction.feePercentage = feePercentage;
        }

        await setDoc(doc(db, "transactions", transactionId), transaction);
      } else {
        console.log(`Transação já existe para fatura ${invoiceId}, pulando criação`);
      }
      
      // Atualiza status de pagamento do aluno
      try {
        const studentRef = doc(db, "profiles", invoice.studentId);
        const studentSnap = await getDoc(studentRef);
        if (studentSnap.exists()) {
          // Busca todas as faturas pendentes do aluno
          const pendingInvoicesQuery = query(
            collection(db, "invoices"),
            where("studentId", "==", invoice.studentId),
            where("status", "in", ["pending", "overdue"])
          );
          const pendingInvoicesSnap = await getDocs(pendingInvoicesQuery);
          
          // Calcula novo status: se tem atrasadas = atrasado, se tem pendentes = pendente, senão = em_dia
          const hasOverdue = pendingInvoicesSnap.docs.some(d => d.data().status === "overdue");
          const newPaymentStatus = hasOverdue ? "atrasado" : 
            pendingInvoicesSnap.docs.length > 0 ? "pendente" : "em_dia";
          
          await updateDoc(studentRef, {
            paymentStatus: newPaymentStatus,
          });
          
          // Verifica se é ingresso de evento (baile ou outro evento) para gerar voucher e confirmar presença
          // Verifica por tipo, descrição começando com "Ingresso:" ou contendo "Ingresso:"
          const isEventTicket = invoice.type === "baile" || 
                                invoice.type === "workshop" ||
                                invoice.type === "outro" ||
                                invoice.description?.startsWith("Ingresso:") || 
                                invoice.description?.includes("Ingresso:");
          
          if (isEventTicket) {
            try {
              // Confirma presença no evento após pagamento
              if (confirmEventAttendanceAfterPayment && invoice.description) {
                try {
                  await confirmEventAttendanceAfterPayment(invoice.id, invoice.studentId, invoice.description);
                  console.log(`[markAsPaid] Presença confirmada no evento após pagamento: ${invoice.description}`);
                } catch (confirmError) {
                  console.warn("Erro ao confirmar presença no evento após pagamento:", confirmError);
                  // Continua mesmo se falhar a confirmação
                }
              }

              // Verifica se já existe voucher para esta fatura
              const existingVoucher = await fetchVoucherByInvoiceId(invoice.id);
              
              if (existingVoucher) {
                console.log("Voucher já existe para esta fatura:", existingVoucher.id);
                // Envia notificação com voucher existente
                await sendNotificationToStudent(invoice.studentId, {
                  type: "voucher",
                  title: `🎉 Voucher Disponível!`,
                  message: `Seu voucher: ${existingVoucher.voucherCode}. Apresente este código na entrada.`,
                  invoiceId,
                  amount: invoice.amount,
                  voucherId: existingVoucher.id,
                  voucherCode: existingVoucher.voucherCode,
                });
              } else if (invoice.isGuestTicket && invoice.parentVoucherId && invoice.guestName) {
                // É um ingresso de acompanhante - busca voucher pai e cria voucher de acompanhante
                console.log("Gerando voucher de acompanhante:", invoice.id);

                // Busca o voucher pai
                const parentVoucherRef = doc(db, "vouchers", invoice.parentVoucherId);
                const parentVoucherSnap = await getDoc(parentVoucherRef);

                if (parentVoucherSnap.exists()) {
                  const parentVoucher = parentVoucherSnap.data() as BaileVoucher;

                  // Cria voucher de acompanhante
                  const guestVoucher = await createGuestVoucher(invoice, parentVoucher, invoice.guestName);

                  // Envia notificação com voucher de acompanhante
                  await sendNotificationToStudent(invoice.studentId, {
                    type: "voucher",
                    title: `🎉 Voucher do Acompanhante Gerado!`,
                    message: `Voucher de ${invoice.guestName}: ${guestVoucher.voucherCode}. Apresente na entrada.`,
                    invoiceId,
                    amount: invoice.amount,
                    voucherId: guestVoucher.id,
                    voucherCode: guestVoucher.voucherCode,
                  });
                } else {
                  console.error("Voucher pai não encontrado:", invoice.parentVoucherId);
                  // Cria voucher normal como fallback
                  const voucher = await createBaileVoucher(invoice);
                  await sendNotificationToStudent(invoice.studentId, {
                    type: "voucher",
                    title: `🎉 Voucher Gerado!`,
                    message: `Voucher: ${voucher.voucherCode}. Apresente este código na entrada.`,
                    invoiceId,
                    amount: invoice.amount,
                    voucherId: voucher.id,
                    voucherCode: voucher.voucherCode,
                  });
                }
              } else {
                // Gera novo voucher normal
                console.log("Gerando voucher para ingresso de evento:", invoice.id);
                const voucher = await createBaileVoucher(invoice);

                // Determina o tipo de evento para a mensagem
                const eventType = invoice.type === "baile" ? "Baile" : "Evento";

                // Envia notificação especial com voucher
                await sendNotificationToStudent(invoice.studentId, {
                  type: "voucher",
                  title: `🎉 Voucher Gerado para ${eventType}!`,
                  message: `Pagamento confirmado! Seu voucher: ${voucher.voucherCode}. Apresente este código na entrada.`,
                  invoiceId,
                  amount: invoice.amount,
                  voucherId: voucher.id,
                  voucherCode: voucher.voucherCode,
                });
              }
            } catch (voucherError) {
              console.error("Erro ao gerar/buscar voucher:", voucherError);
              // Envia notificação normal mesmo se falhar o voucher
              await sendNotificationToStudent(invoice.studentId, {
                type: "payment_confirmed",
                title: "✅ Pagamento Confirmado",
                message: `Seu pagamento de ${formatCurrency(invoice.amount)} foi confirmado com sucesso! Obrigado.`,
                invoiceId,
                amount: invoice.amount,
              });
            }
          } else {
            // Envia notificação de pagamento confirmado normal (não é ingresso de evento)
            await sendNotificationToStudent(invoice.studentId, {
              type: "payment_confirmed",
              title: "✅ Pagamento Confirmado",
              message: `Seu pagamento de ${formatCurrency(invoice.amount)} foi confirmado com sucesso! Obrigado.`,
              invoiceId,
              amount: invoice.amount,
            });
          }
        }
      } catch (e) {
        console.warn("Erro ao atualizar status do aluno ou enviar notificação:", e);
      }

      // Cria atividade para o log de atividades recentes (sempre, mesmo se houver erro nas notificações)
      try {
        await createActivity({
          type: "payment",
          title: "Pagamento confirmado",
          description: `${invoice.studentName} pagou ${invoice.description || "mensalidade"}`,
          metadata: {
            studentId: invoice.studentId,
            studentName: invoice.studentName,
            invoiceId,
            amount: invoice.amount,
          },
        });
      } catch (e) {
        console.warn("Erro ao criar atividade:", e);
      }
    }
  }, [profile, getPaymentSettings, calculateMercadoPagoFee, sendNotificationToStudent, fetchVoucherByInvoiceId, createBaileVoucher, createGuestVoucher, createActivity, confirmEventAttendanceAfterPayment]);

  const markAsOverdue = useCallback(async (invoiceId: string): Promise<void> => {
    const ref = doc(db, "invoices", invoiceId);
    const invoiceSnap = await getDoc(ref);
    
    if (!invoiceSnap.exists()) {
      throw new Error("Fatura não encontrada");
    }
    
    const invoice = invoiceSnap.data() as Invoice;
    
    await updateDoc(ref, {
      status: "overdue",
      updatedAt: Date.now(),
    });
    
    // Envia notificação de atraso para o aluno
    await sendNotificationToStudent(invoice.studentId, {
      type: "overdue",
      title: "Pagamento em atraso",
      message: `Sua mensalidade de ${formatCurrency(invoice.amount)} está em atraso. Regularize seu pagamento.`,
      invoiceId,
      amount: invoice.amount,
      dueDate: invoice.lateDueDate || invoice.dueDate,
    });
  }, [sendNotificationToStudent]);

  // ========== TRANSAÇÕES ==========

  const createTransaction = useCallback(async (
    data: Omit<Transaction, "id" | "createdAt" | "createdBy">
  ): Promise<string> => {
    if (!profileUid) throw new Error("Usuário não autenticado");

    const id = generateId("TXN");
    const transaction: Transaction = {
      ...data,
      id,
      createdAt: Date.now(),
      createdBy: profileUid,
    };

    await setDoc(doc(db, "transactions", id), transaction);
    return id;
  }, [profileUid]);

  const fetchTransactions = useCallback(async (
    filters?: { type?: "income" | "expense"; month?: string }
  ): Promise<Transaction[]> => {
    try {
      const transactionsRef = collection(db, "transactions");
      let constraints: any[] = [];

      if (filters?.type) {
        constraints.push(where("type", "==", filters.type));
      }

      const q = constraints.length > 0 
        ? query(transactionsRef, ...constraints)
        : query(transactionsRef);
      
      const snap = await getDocs(q);
      let transactions = snap.docs.map(d => d.data() as Transaction);

      // Filtra por mês no cliente (para evitar índice composto)
      if (filters?.month) {
        transactions = transactions.filter(t => t.date.startsWith(filters.month!));
      }
      
      // Ordena por data
      return transactions.sort((a, b) => 
        new Date(b.date).getTime() - new Date(a.date).getTime()
      );
    } catch (e) {
      console.error("Erro ao buscar transações:", e);
      return [];
    }
  }, []);

  const deleteTransaction = useCallback(async (id: string): Promise<void> => {
    await deleteDoc(doc(db, "transactions", id));
  }, []);

  // ========== PIX ==========

  const generatePixCode = useCallback(async (invoice: Invoice): Promise<string> => {
    // Busca configurações usando getPaymentSettings diretamente (já definido antes)
    const settings = await getPaymentSettings();
    
    if (!settings?.pixKey) {
      throw new Error("Chave PIX não configurada");
    }

    const txId = invoice.id.replace(/[^a-zA-Z0-9]/g, "").substring(0, 25);
    
    const pixCode = generatePixPayload(
      settings.pixKey,
      settings.pixKeyType,
      settings.pixReceiverName,
      settings.pixCity,
      invoice.amount,
      txId,
      invoice.description
    );

    // Salva o código PIX na fatura
    await updateInvoice(invoice.id, {
      pixCode,
      pixExpiration: Date.now() + (24 * 60 * 60 * 1000), // 24 horas
    });

    return pixCode;
  }, [updateInvoice, getPaymentSettings]);

  // ========== RELATÓRIOS ==========

  const getFinancialSummary = useCallback(async (month?: string): Promise<FinancialSummary> => {
    const currentMonth = month || new Date().toISOString().slice(0, 7);
    
    // Busca faturas do mês
    const invoices = await fetchInvoices({ month: currentMonth });
    
    // Busca transações do mês
    const transactions = await fetchTransactions({ month: currentMonth });

    const paid = invoices.filter(i => i.status === "paid");
    const pending = invoices.filter(i => i.status === "pending");
    const overdue = invoices.filter(i => i.status === "overdue");

    // Calcula valores brutos (antes das taxas)
    const totalReceived = transactions
      .filter(t => t.type === "income")
      .reduce((sum, t) => sum + t.amount, 0);

    // Calcula total de taxas deduzidas e valor líquido recebido (valor que está na conta)
    const incomeTransactions = transactions.filter(t => t.type === "income");

    // Busca configurações de pagamento para calcular taxas de transações antigas
    const settings = await getPaymentSettings();
    
    const totalFees = incomeTransactions.reduce((sum, t) => {
      // Se já tem fee calculado, usa ele
      if (t.fee !== undefined && t.fee !== null) {
        return sum + t.fee;
      }
      // Se não tem fee mas é pagamento via Mercado Pago, calcula a taxa
      if (t.paymentMethod === "pix_mercadopago" || t.paymentMethod === "card") {
        const { fee } = calculateMercadoPagoFee(t.amount, t.paymentMethod || "pix_mercadopago", settings);
        return sum + fee;
      }
      return sum;
    }, 0);
    
    const totalReceivedNet = incomeTransactions.reduce((sum, t) => {
      // Usa amountNet se disponível (valor líquido após taxa)
      if (t.amountNet !== undefined && t.amountNet !== null) {
        return sum + t.amountNet;
      }
      // Se não tem amountNet mas é pagamento via Mercado Pago, calcula o valor líquido
      if (t.paymentMethod === "pix_mercadopago" || t.paymentMethod === "card") {
        const { amountNet } = calculateMercadoPagoFee(t.amount, t.paymentMethod || "pix_mercadopago", settings);
        return sum + amountNet;
      }
      // Para outros métodos de pagamento (sem taxa), usa o valor bruto
      return sum + t.amount;
    }, 0);

    const totalExpenses = transactions
      .filter(t => t.type === "expense")
      .reduce((sum, t) => sum + t.amount, 0);

    const totalPending = pending.reduce((sum, i) => sum + i.amount, 0);
    const totalOverdue = overdue.reduce((sum, i) => sum + i.amount, 0);

    return {
      totalReceived, // valor bruto recebido (antes das taxas)
      totalFees, // total de taxas deduzidas
      totalReceivedNet, // valor líquido recebido (após taxas) - valor que está na conta do banco
      totalPending,
      totalOverdue,
      totalExpenses,
      balance: totalReceivedNet - totalExpenses, // saldo líquido (valor na conta - despesas)
      invoicesCount: {
        paid: paid.length,
        pending: pending.length,
        overdue: overdue.length,
      },
    };
  }, [fetchInvoices, fetchTransactions, getPaymentSettings, calculateMercadoPagoFee]);

  // Calcula preço baseado no número de turmas
  const calculatePriceForStudent = useCallback((
    classCount: number, 
    settings: PaymentSettings
  ): { earlyPrice: number; regularPrice: number; discount: number } => {
    const count = Math.max(1, Math.min(classCount, 4)); // Limite de 1 a 4 turmas
    
    const tier = settings.tierPricing?.find(t => t.classes === count) 
      || settings.tierPricing?.[count - 1]
      || { earlyPrice: settings.monthlyFee, regularPrice: settings.monthlyFee };
    
    return {
      earlyPrice: tier.earlyPrice,
      regularPrice: tier.regularPrice,
      discount: tier.regularPrice - tier.earlyPrice,
    };
  }, []);

  // Gera fatura automática para um aluno
  const generateInvoiceForStudent = useCallback(async (
    student: Profile,
    month: string // "2025-01"
  ): Promise<Invoice | null> => {
    if (!profile) throw new Error("Usuário não autenticado");
    
    const settings = await getPaymentSettings();
    if (!settings) throw new Error("Configurações de pagamento não encontradas");
    
    // Busca turmas ativas onde o aluno está realmente inscrito (pela lista de studentIds da turma)
    const classesRef = collection(db, "classes");
    const classesSnap = await getDocs(classesRef);
    const activeClasses = classesSnap.docs
      .map(doc => doc.data() as Class)
      .filter(c => c.active && c.studentIds?.includes(student.uid));
    
    const classCount = activeClasses.length;
    const classIds = activeClasses.map(c => c.id);
    
    if (classCount === 0) {
      console.log(`Aluno ${student.name} não está em nenhuma turma ativa`);
      return null;
    }
    
    // Verifica se já existe fatura para este mês
    const existing = await fetchInvoices({ studentId: student.uid, month });
    if (existing.length > 0) {
      console.log(`Fatura já existe para ${student.name} em ${month}`);
      return existing[0];
    }
    
    const prices = calculatePriceForStudent(classCount, settings);
    
    // Calcula as datas de vencimento
    const [year, monthNum] = month.split("-").map(Number);
    const dueDayStr = settings.dueDayOfMonth.toString().padStart(2, "0");
    const lateDayStr = settings.latePaymentDeadline.toString().padStart(2, "0");
    const dueDate = `${year}-${monthNum.toString().padStart(2, "0")}-${dueDayStr}`;
    const lateDueDate = `${year}-${monthNum.toString().padStart(2, "0")}-${lateDayStr}`;
    
    // Verifica se ainda está no período de desconto
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const earlyDeadline = new Date(dueDate + "T23:59:59");
    earlyDeadline.setHours(23, 59, 59, 999);
    const isEarlyPayment = today <= earlyDeadline;
    
    const currentAmount = isEarlyPayment ? prices.earlyPrice : prices.regularPrice;
    const discountValue = isEarlyPayment ? prices.discount : 0;
    
    // Monta descrição detalhada
    const description = `Mensalidade ${getMonthName(monthNum)}/${year} - ${classCount} turma${classCount > 1 ? "s" : ""}`;
    
    const id = generateId("INV");
    const invoice: Invoice = {
      id,
      studentId: student.uid,
      studentName: student.name,
      studentEmail: student.email,
      amount: currentAmount,
      originalAmount: prices.regularPrice,
      discountAmount: discountValue,
      description,
      dueDate,
      lateDueDate,
      status: "pending",
      referenceMonth: month,
      classIds,
      classCount,
      createdAt: Date.now(),
      createdBy: profile.uid,
      isAutoGenerated: true,
    };
    
    await setDoc(doc(db, "invoices", id), invoice);
    
    // Atualiza status de pagamento do aluno
    try {
      const studentRef = doc(db, "profiles", student.uid);
      const studentSnap = await getDoc(studentRef);
      if (studentSnap.exists()) {
        // Busca todas as faturas pendentes do aluno
        const pendingInvoicesQuery = query(
          collection(db, "invoices"),
          where("studentId", "==", student.uid),
          where("status", "in", ["pending", "overdue"])
        );
        const pendingInvoicesSnap = await getDocs(pendingInvoicesQuery);
        
        // Calcula novo status: se tem atrasadas = atrasado, se tem pendentes = pendente, senão = em_dia
        const hasOverdue = pendingInvoicesSnap.docs.some(d => d.data().status === "overdue");
        const newPaymentStatus = hasOverdue ? "atrasado" : 
          pendingInvoicesSnap.docs.length > 0 ? "pendente" : "em_dia";
        
        await updateDoc(studentRef, {
          paymentStatus: newPaymentStatus,
        });
      }
    } catch (e) {
      console.warn("Erro ao atualizar status do aluno:", e);
    }
    
    // Envia notificação para o aluno
    await sendNotificationToStudent(student.uid, {
      type: "billing",
      title: "Nova mensalidade gerada",
      message: `Sua mensalidade de ${formatCurrency(currentAmount)} para ${formatDateSafe(month)} está disponível.`,
      invoiceId: id,
      amount: currentAmount,
      dueDate,
    });
    
    // Cria atividade para o log de atividades recentes
    try {
      const activityId = generateId("ACT");
      const activitiesRef = collection(db, "activities");
      await setDoc(doc(activitiesRef, activityId), {
        id: activityId,
        type: "invoice_generated",
        title: "Cobrança gerada",
        description: `Mensalidade de ${formatCurrency(currentAmount)} gerada para ${student.name}`,
        timestamp: Date.now(),
        metadata: {
          studentId: student.uid,
          studentName: student.name,
          invoiceId: id,
          amount: currentAmount,
        },
        read: false,
        createdBy: profile.uid,
      });
    } catch (e) {
      console.warn("Erro ao criar atividade:", e);
    }
    
    return invoice;
  }, [profile, getPaymentSettings, calculatePriceForStudent, fetchInvoices, sendNotificationToStudent]);

  // ========== COBRANÇAS EM LOTE ==========

  const generateMonthlyInvoices = useCallback(async (
    students: Profile[],
    month: string
  ): Promise<number> => {
    if (!profile) throw new Error("Usuário não autenticado");

    // Filtra apenas alunos ativos com turmas
    const eligibleStudents = students.filter(
      s => s.enrollmentStatus === "ativo" && s.classes && s.classes.length > 0
    );

    // Cria faturas
    let created = 0;
    for (const student of eligibleStudents) {
      try {
        const invoice = await generateInvoiceForStudent(student, month);
        if (invoice) created++;
      } catch (e) {
        console.error(`Erro ao criar fatura para ${student.name}:`, e);
      }
    }

    return created;
  }, [profile, generateInvoiceForStudent]);

  // ========== ATUALIZAÇÃO AUTOMÁTICA ==========

  const updateOverdueInvoices = useCallback(async (): Promise<number> => {
    const pendingInvoices = await fetchInvoices({ status: "pending" });
    
    let updated = 0;
    for (const invoice of pendingInvoices) {
      // Usa lateDueDate se disponível, senão usa dueDate
      const deadlineDate = invoice.lateDueDate || invoice.dueDate;
      if (isOverdue(deadlineDate)) {
        await markAsOverdue(invoice.id);
        updated++;
      }
    }

    return updated;
  }, [fetchInvoices, markAsOverdue]);

  // ==================== LISTENERS EM TEMPO REAL ====================

  // Listener para faturas de um aluno específico
  const subscribeToInvoices = useCallback((
    studentId: string,
    callback: (invoices: Invoice[]) => void
  ): (() => void) => {
    const invoicesRef = collection(db, "invoices");
    
    // Query simples sem orderBy para evitar necessidade de índice composto
    // A ordenação é feita no cliente
    const q = query(
      invoicesRef, 
      where("studentId", "==", studentId)
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const invoices = snapshot.docs.map(doc => doc.data() as Invoice);
      // Ordena por data de criação (mais recente primeiro) no cliente
      invoices.sort((a, b) => b.createdAt - a.createdAt);
      callback(invoices);
    }, (error) => {
      console.error("Erro no listener de faturas:", error);
      // Em caso de erro, retorna array vazio para não deixar carregando infinitamente
      callback([]);
    });

    return unsubscribe;
  }, []);

  // Listener para TODAS as faturas (usado pelo master)
  const subscribeToAllInvoices = useCallback((
    callback: (invoices: Invoice[]) => void,
    filters?: { status?: PaymentStatus | PaymentStatus[]; month?: string }
  ): (() => void) => {
    const invoicesRef = collection(db, "invoices");
    const constraints = [];

    if (profileRole === "student" && profileUid) {
      constraints.push(where("studentId", "==", profileUid));
    }

    if (filters?.status) {
      if (Array.isArray(filters.status)) {
        constraints.push(where("status", "in", filters.status));
      } else {
        constraints.push(where("status", "==", filters.status));
      }
    }

    if (filters?.month) {
      constraints.push(where("referenceMonth", "==", filters.month));
    }

    const source = constraints.length > 0
      ? query(invoicesRef, ...constraints)
      : invoicesRef;
    
    // Query sem filtros complexos para evitar necessidade de índices
    const unsubscribe = onSnapshot(source, (snapshot) => {
      const invoices = snapshot.docs.map(doc => doc.data() as Invoice);
      
      
      
      
      // Ordena por data de criação (mais recente primeiro)
      invoices.sort((a, b) => b.createdAt - a.createdAt);
      callback(invoices);
    }, (error) => {
      console.error("Erro no listener de todas as faturas:", error);
      callback([]);
    });

    return unsubscribe;
  }, [profileRole, profileUid]);

  // Listener para configurações de pagamento
  const subscribeToSettings = useCallback((
    callback: (settings: PaymentSettings | null) => void
  ): (() => void) => {
    const settingsRef = doc(db, "settings", "payment");

    const unsubscribe = onSnapshot(settingsRef, (snapshot) => {
      if (snapshot.exists()) {
        const data = snapshot.data() as PaymentSettings;
        // Garante que tierPricing existe
        if (!data.tierPricing || data.tierPricing.length === 0) {
          data.tierPricing = [
            { classes: 1, earlyPrice: 990, regularPrice: 1090 },
            { classes: 2, earlyPrice: 1780, regularPrice: 1980 },
            { classes: 3, earlyPrice: 2520, regularPrice: 2820 },
            { classes: 4, earlyPrice: 3160, regularPrice: 3560 },
          ];
        }
        callback(data);
      } else {
        // Retorna configurações padrão
        callback({
          monthlyFee: 1090,
          pixKey: "",
          pixKeyType: "cpf",
          pixReceiverName: "CDMF",
          pixCity: "SAO PAULO",
          dueDayOfMonth: 1,
          gracePeriodDays: 7,
          latePaymentDeadline: 8,
          tierPricing: [
            { classes: 1, earlyPrice: 990, regularPrice: 1090 },
            { classes: 2, earlyPrice: 1780, regularPrice: 1980 },
            { classes: 3, earlyPrice: 2520, regularPrice: 2820 },
            { classes: 4, earlyPrice: 3160, regularPrice: 3560 },
          ],
        });
      }
    }, (error) => {
      console.error("Erro no listener de configurações:", error);
      callback(null);
    });

    return unsubscribe;
  }, []);

  // Verificação periódica em background para pagamentos PIX pendentes
  // Esta verificação funciona mesmo quando o usuário não está na tela de pagamentos
  // O listener do Firestore detectará as mudanças e atualizará a UI automaticamente
  useEffect(() => {
    // Só executa para alunos logados
    if (!profileUid || profileRole !== "student") return;

    let intervalId: ReturnType<typeof setInterval> | null = null;
    let cleanup: (() => void) | null = null;

    // Importa dinamicamente para evitar dependência circular
    import("../services/mercadoPagoService").then((module) => {
      const { checkMercadoPagoPayment, USE_MERCADO_PAGO: MP_ENABLED } = module;

      if (!MP_ENABLED) return;

      // Verifica a cada 30 segundos as invoices pendentes do próprio aluno com mpPaymentId
      intervalId = setInterval(async () => {
        try {
          const invoicesRef = collection(db, "invoices");
          // Busca apenas invoices do próprio aluno (segurança: regras do Firestore garantem isso)
          // IMPORTANTE: Adiciona filtro por studentId para permitir que as regras do Firestore funcionem
          const q = query(
            invoicesRef,
            where("studentId", "==", profileUid),
            where("status", "in", ["pending", "overdue"])
          );
          
          const snapshot = await getDocs(q);
          const pendingInvoices = snapshot.docs
            .map(doc => ({ id: doc.id, ...doc.data() } as Invoice))
            .filter(inv => inv.mpPaymentId); // Apenas invoices com mpPaymentId
          
          // Verifica cada invoice pendente
          for (const invoice of pendingInvoices) {
            try {
              const result = await checkMercadoPagoPayment(invoice.id);
              // Se o pagamento foi confirmado, a função checkMercadoPagoPayment
              // já atualiza o status no Firestore via Cloud Function
              // O listener do Firestore detectará a mudança e atualizará a UI
              if (result.isPaid) {
                // Log silencioso - apenas para debug se necessário
                // console.log(`[BackgroundPaymentCheck] Pagamento confirmado para fatura ${invoice.id}`);
              }
            } catch (e) {
              // Erro silencioso para não poluir logs
              // console.debug(`[BackgroundPaymentCheck] Erro ao verificar fatura ${invoice.id}:`, e);
            }
          }
        } catch (e) {
          // Erro geral - apenas log se for erro de permissão (esperado se não for aluno)
          if ((e as any)?.code !== "permission-denied") {
            // console.error("[BackgroundPaymentCheck] Erro geral:", e);
          }
        }
      }, 30000); // Verifica a cada 30 segundos
      
      cleanup = () => {
        if (intervalId) clearInterval(intervalId);
      };
    }).catch((e) => {
      // console.error("[BackgroundPaymentCheck] Erro ao importar serviço:", e);
    });

    return () => {
      if (cleanup) cleanup();
      if (intervalId) clearInterval(intervalId);
    };
  }, [profileUid, profileRole]);

  // Limpa todos os dados financeiros (faturas, transações e status dos alunos)
  const clearAllFinancialData = useCallback(async (): Promise<{ invoices: number; transactions: number; studentsUpdated: number }> => {
    if (!profileUid || profileRole !== "master") {
      throw new Error("Apenas o administrador pode limpar dados financeiros");
    }

    let invoicesDeleted = 0;
    let transactionsDeleted = 0;
    let studentsUpdated = 0;

    // 1. Deleta todas as faturas
    const invoicesSnap = await getDocs(collection(db, "invoices"));
    for (const docSnap of invoicesSnap.docs) {
      await deleteDoc(doc(db, "invoices", docSnap.id));
      invoicesDeleted++;
    }

    // 2. Deleta todas as transações
    const transactionsSnap = await getDocs(collection(db, "transactions"));
    for (const docSnap of transactionsSnap.docs) {
      await deleteDoc(doc(db, "transactions", docSnap.id));
      transactionsDeleted++;
    }

    // 3. Atualiza o status de pagamento de todos os alunos para "sem_cobranca"
    // e limpa as notificações de pagamento
    const studentsQuery = query(collection(db, "profiles"), where("role", "==", "student"));
    const studentsSnap = await getDocs(studentsQuery);
    for (const docSnap of studentsSnap.docs) {
      await updateDoc(doc(db, "profiles", docSnap.id), {
        paymentStatus: "sem_cobranca",
        pendingNotifications: [],
      });
      studentsUpdated++;
    }

    return { invoices: invoicesDeleted, transactions: transactionsDeleted, studentsUpdated };
  }, [profileUid, profileRole]);

  // Migra transações antigas sem amountNet definido
  const migrateTransactionsAmountNet = useCallback(async (): Promise<{ updated: number; skipped: number }> => {
    if (profileRole !== "master") {
      throw new Error("Apenas o master pode executar migrações");
    }

    console.log("[Migração] Iniciando migração de transações...");

    const transactionsRef = collection(db, "transactions");
    const q = query(transactionsRef, where("type", "==", "income"));
    const snap = await getDocs(q);

    console.log(`[Migração] Encontradas ${snap.docs.length} transações de entrada`);

    const settings = await getPaymentSettings();
    let updated = 0;
    let skipped = 0;

    for (const docSnap of snap.docs) {
      const transaction = docSnap.data() as Transaction;

      const method = transaction.paymentMethod || "cash";

      // Calcula o amountNet, fee e feePercentage baseado no método de pagamento
      const { amountNet, fee, feePercentage } = calculateMercadoPagoFee(
        transaction.amount,
        method,
        settings
      );

      // Verifica se precisa atualizar (amountNet diferente ou ausente)
      const needsUpdate =
        transaction.amountNet === undefined ||
        transaction.amountNet === null ||
        transaction.amountNet !== amountNet;

      if (!needsUpdate) {
        console.log(`[Migração] Transação ${transaction.id} já está correta: amountNet=${transaction.amountNet}, fee=${transaction.fee} - pulando`);
        skipped++;
        continue;
      }

      console.log(`[Migração] Transação ${transaction.id}: amount=${transaction.amount}, method=${method}, amountNet atual=${transaction.amountNet}, amountNet correto=${amountNet}, fee=${fee}`);

      // Atualiza a transação com todos os campos calculados
      const updateData: any = { amountNet };

      // Adiciona ou remove fee e feePercentage baseado se há taxa
      if (fee > 0) {
        updateData.fee = fee;
        updateData.feePercentage = feePercentage;
      } else {
        // Remove campos de taxa se não houver taxa (pagamento em dinheiro)
        updateData.fee = null;
        updateData.feePercentage = null;
      }

      try {
        await updateDoc(doc(db, "transactions", transaction.id), updateData);
        console.log(`[Migração] ✅ Transação ${transaction.id} atualizada com sucesso`);
        updated++;
      } catch (error) {
        console.error(`[Migração] ❌ Erro ao atualizar transação ${transaction.id}:`, error);
      }
    }

    console.log(`[Migração] 🎉 Migração concluída: ${updated} transações atualizadas, ${skipped} puladas`);
    return { updated, skipped };
  }, [profileRole, getPaymentSettings, calculateMercadoPagoFee]);

  // ==================== VALUE ====================

  const value = useMemo(
    () => ({
      // Faturas
      createInvoice,
      fetchInvoices,
      updateInvoice,
      deleteInvoice,
      markAsPaid,
      markAsOverdue,
      // Transações
      createTransaction,
      fetchTransactions,
      deleteTransaction,
      // PIX
      generatePixCode,
      // Relatórios
      getFinancialSummary,
      // Lote
      generateMonthlyInvoices,
      updateOverdueInvoices,
      // Configurações
      getPaymentSettings,
      updatePaymentSettings,
      // Cálculo de preços
      calculatePriceForStudent,
      // Geração automática
      generateInvoiceForStudent,
      // Listeners em tempo real
      subscribeToInvoices,
      subscribeToAllInvoices,
      subscribeToSettings,
      // Administração
      clearAllFinancialData,
      migrateTransactionsAmountNet,
      // Vouchers de baile
      fetchStudentVouchers,
      fetchVoucherByInvoiceId,
      fetchVoucherByEventId,
      fetchAllVouchers,
      useVoucher,
      createBaileVoucher,
      cancelVoucher,
      deleteVoucher,
      // Vouchers de acompanhante
      createGuestInvoice,
      createGuestVoucher,
      fetchGuestVouchers,
    }),
    [
      createInvoice,
      fetchInvoices,
      updateInvoice,
      deleteInvoice,
      markAsPaid,
      markAsOverdue,
      createTransaction,
      fetchTransactions,
      deleteTransaction,
      generatePixCode,
      getFinancialSummary,
      generateMonthlyInvoices,
      updateOverdueInvoices,
      getPaymentSettings,
      updatePaymentSettings,
      calculatePriceForStudent,
      generateInvoiceForStudent,
      subscribeToInvoices,
      subscribeToAllInvoices,
      subscribeToSettings,
      clearAllFinancialData,
      migrateTransactionsAmountNet,
      fetchStudentVouchers,
      fetchVoucherByInvoiceId,
      fetchVoucherByEventId,
      fetchAllVouchers,
      useVoucher,
      createBaileVoucher,
      cancelVoucher,
      deleteVoucher,
      createGuestInvoice,
      createGuestVoucher,
      fetchGuestVouchers,
    ]
  );

  return <PaymentContext.Provider value={value}>{children}</PaymentContext.Provider>;
}

export function usePayment() {
  const ctx = useContext(PaymentContext);
  if (!ctx) throw new Error("usePayment must be used within <PaymentProvider>");
  return ctx;
}

